task:
  container:
    dockerfile: Dockerfile
    cpu: 2
    greedy: true
  registry_cache:
    folder: $CARGO_HOME/registry
  target_cache:
    folder: target
  matrix:
    - name: Build
      build_script: cargo build --release
      binaries_artifacts:
        path: target/release/cotton
    - name: Check
      script: cargo fmt -- --check && cargo clippy