task:
  container:
    dockerfile: Dockerfile
    cpu: 8
    greedy: true
  registry_cache:
    folder: $CARGO_HOME/registry
  target_cache:
    folder: target
  matrix:
    - name: Build
      build_script: cargo build --release
    - name: Format
      fmt_script: cargo fmt -- --check
    - name: Clippy
      clippy_script: cargo clippy